import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import {
  contactFooter,
  helpFooter,
  homeFooter,
  links,
  serviceFooter,
  socialMedia,
} from "@/Data/data";
import LoaderWrapper from "@/components/LoaderWrapper.tsx";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tuscany",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      <body className={`overflow-x-hidden ${openSans.variable}`}>
        <LoaderWrapper>
          <NavBar links={links} />
          {children}
          <Footer
            services={serviceFooter}
            home={homeFooter}
            help={helpFooter}
            contact={contactFooter}
            social={socialMedia}
          />
        </LoaderWrapper>
      </body>
    </html>
  );
}
