import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import {
  contactFooter,
  helpFooter,
  homeFooter,
  links,
  serviceFooter,
  socialMedia,
} from "@/Data/data";
import LogoLoader from "@/components/LogoLoader";
import AOSInit from "@/components/AOSInit";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
     <AOSInit/>
        <LogoLoader />
        <NavBar links={links} />
        {children}
        <Footer
          services={serviceFooter}
          home={homeFooter}
          help={helpFooter}
          contact={contactFooter}
          social={socialMedia}
        />
      </body>
    </html>
  );
}
